schema_ver: "2025-09-30"
asof:
  weekly_anchor: "W-FRI"

validation:
  cv:
    embargo_days: 5
  data:
    calendar_path: "cal/trading_days.csv"

acceptance:
  sharpe_min_after_costs: 1.8
  max_dd_max: 0.20
  wf_pass_ratio_min: 0.80
  dsr_min_after_costs: 0.0

alpha_quality:
  rank_ic_weekly_min: 0.03
  ic_by_regime_nonnegative: true
  orthogonalization_corr_abs_max: 0.7

regime:
  required: ["trend_up","vol_up","liq_up"]
  report_by_regime: true

execution_checks:
  replay_mae_bps_max: 2
  backtest_vs_replay_match_min: 0.99

live_controls:
  killswitch:
    drawdown_warn: -0.10
    drawdown_stop: -0.15

capacity:
  max_participation_pct: 5.0
  max_turnover_annual: 5.0
  single_name_weight_max: 0.05

leverage_cap: 1.3
