repos:
  - repo: local
    hooks:
      - id: check-canonical-layout
        name: Check canonical layout
        entry: pwsh -NoProfile -ExecutionPolicy Bypass -File tools/Check-CanonicalLayout.ps1 -Strict
        language: system
        pass_filenames: false
