# configs/backtest_topN_template.yaml
# Base settings; run_all_backtests.py will clone and override 'topN' & 'rebalance' per grid.
topN: 50
rebalance: M
fees: 0.0005
slippage: 0.0005
delay: 1
start: "2015-01-01"
end:   "2020-12-31"
